name: Deploy to Vercel (apps/builder)

on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup PNPM
        uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: pnpm

      - name: Install deps (workspace root)
        run: pnpm install --prefer-offline

      - name: Build workspace packages
        run: pnpm -w --filter='packages/*' build

      - name: Pull Vercel env
        working-directory: apps/builder
        run: npx vercel@latest pull --yes --environment=production

      - name: Build (prebuilt output)
        working-directory: apps/builder
        run: npx vercel@latest build

      - name: Deploy to Vercel (Production)
        working-directory: apps/builder
        run: npx vercel@latest deploy --prebuilt --prod